### PR TITLE
[bugfix] #49 Fix last insert id return type in case of dblib (3.x)

### PR DESCRIPTION
**Pull request by szhajdu**
Follow up on https://github.com/Codeception/module-db/pull/51

See https://github.com/Codeception/module-db/pull/55 for details

### CODE REVIEW

**Comment by szhajdu** [comment]
I wanted to check in on the status of my pull request. I would greatly appreciate any feedback you might have on the fix I've proposed. Thanks for your time and consideration!

**Comment by DavertMik** [comment]
@Naktibalda @TavoNiievez are we ok to merge this?

**Comment by DavertMik** [comment]
@szhajdu sorry, looks like no one currently can merge PR, but I can make you a maintainer instead
how does it sound?

**Comment by szhajdu** [comment]
OK, I'm in.

**Comment by DavertMik** [comment]
@szhajdu please check, I sent you invite
I think you can make a release

@Naktibalda FYI ^

**Pull request merged**
