### PR TITLE
[bugfix] #49 Fix last insert id return type in case of FreeTDS (2.x)

### PR DESCRIPTION
**Pull request by szhajdu**
The sqlsrv extension works fine, but in case of FreeTDS, lastInsertid returns with false when no auto increment on table.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@Naktibalda

**Comment by Naktibalda** [comment]
Thanks for the effort, now please merge the changes from 2.x branch and fix the tests.

https://github.com/Codeception/module-db/pull/48 added new binary field to users table, so you have to add it to mssql.sql.

Also it seems that MSSQL driver can't handle binary parameters, can you fix that?

https://github.com/Codeception/module-db/actions/runs/4454329549/jobs/7823434721
>  [PDOException] SQLSTATE[IMSSP]: An error occurred translating string for input param 1 to UCS-2: Error code 0xB

**Comment by szhajdu** [comment]
I have reviewed the issue and it appears that the solution may be more complex.

For the sqlsrv driver, we will need to use `$pdoStatement->bindParam($i, $param, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);` in order to properly handle binary parameters. However, this will require some modifications to the `Codeception\Lib\Driver\Db::executeQuery` method in order to detect whether sqlsrv is being used. Would you happen to have any suggestions on how to approach this? Would it be appropriate to override the method?

Furthermore, I have discovered a bug related to dblib: https://github.com/php/php-src/issues/10312. So related tests cannot be fixed until it is fixed in the driver itself.

I would appreciate your input on how to proceed. Thank you.

**Comment by Naktibalda** [comment]
I think that overriding `executeQuery` in SqlSrv driver is fine.

If tests can't be fixed, they can be skipped.
```
if ($this instanceof SqlSrv) {
   $this->markTestSkipped('Not supported by SqlSrv');
}
```

Failing binary assertions must be moved to separate methods.

**Pull request closed without merging**
